name: GitHub Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive  # Fetch Hugo themes (true OR recursive)

      - name: Hugo Deploy GitHub Pages
        uses: benmatselby/hugo-deploy-gh-pages@master
        env:
          HUGO_VERSION: 0.84.4
          HUGO_EXTENDED: true
          TARGET_REPO: aureliendossantos/wiki
          TARGET_BRANCH: gh-pages
          TOKEN: ${{ secrets.HUGO_BUILD_TOKEN }}
